site_name: Emilio Benenati
site_description: Personal website
site_url: https://bemilio.github.io
theme:
    # icon:
    name: material
    palette:
        primary: cyan
        accent: cyan
        scheme: slate
    font:
        text: Montserrat
plugins:
    - blog
    - include-markdown
    - search
    - git-revision-date-localized

markdown_extensions:
  - attr_list

nav:
    - "": index.md
    - Publications: pub.md
    - Blog:
        - blog/index.md
    - About: about.md


# extra:
#   social:
